from .start import start
from .ping import ping
from .today import today
from .tomorrow import tomorrow
from .week import week
from .verify import verify
from .krutomer import krutometr
from .kogda_strad import kogda_strad
from .upd import upd