from .start import start
from .ping import ping
from .today import today
from .verify import verify
from .krutomer import krutometr
from .kogda_strad import kogda_strad
from .kogda_wd import kogda_wd
from .upd import upd
from .help import help
from .vlasuka import vlasuka